### PR TITLE
update the image in README

### PR DESCRIPTION
**Pull request by sanette**
just to hopefully look more modern

(cf https://github.com/sanette/graphics to see how it looks like)

### CODE REVIEW

**Comment by xavierleroy** [comment]
I'm all for modernity, but on my browser (Firefox 77, Linux)   https://github.com/sanette/graphics looks all wrong:

Screenshot from 2020-06-20 18-18-09

**Comment by sanette** [comment]
oops indeed. weird. I also use Firefox 77 under linux, and it looks good

Screenshot_20200620_232002

**Comment by sanette** [comment]
I can upload a png version, it will be safer than svg; (however it on my hipdi screen it's not as good as svg.)

**Comment by sanette** [comment]
I have put the png. @xavierleroy is this better for you?
For me it's less sharp than svg, but acceptable I think.

**Comment by xavierleroy** [comment]
I think I found the issue: in my Firefox preferences I have "minimal font size" set to 14pt, and the SVG renderer honors this constraint in a weird way (the font size ends up being 36pt at least).

Looks like an old bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=935056 (first sighting in https://bugzilla.mozilla.org/show_bug.cgi?id=358032 14 years ago) with a promised fix in Firefox 78.

**Comment by sanette** [comment]
I see. Testing with chromium and with qutebrowser, the svg looks OK on both.
That's too bad, but I guess we have to stick to png until the Firefox issue is solved.

**Comment by jeremiedimino** [comment]
Neither svg nor png are modern enough, it should be an OCaml program compiled to javascript that does the rendering when you load the page :smile:

**Comment by sanette** [comment]
@jeremiedimino feel free to do it;)
meanwhile do you want to commit the new png image?

**Comment by jeremiedimino** [comment]
Sure. The svg is still in the PR, shouldn't it be removed?

**Comment by sanette** [comment]
ok, done.

**Comment by jeremiedimino** [comment]
Thanks

**Pull request merged**
